//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fussball
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FussballBundesligaDatenEntities1 : DbContext
    {
        public FussballBundesligaDatenEntities1()
            : base("name=FussballBundesligaDatenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tabelle> Tabelles { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Tipp> Tipps { get; set; }
    }
}
